name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: testExpressions
      id: testexpressions
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testExpressions
        setup-command: ''
        command: gradle test --tests ExpressionsTest.testExpressionsHomework
        timeout: 1
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTEXPRESSIONS_RESULTS: "${{steps.testexpressions.outputs.result}}"
      with:
        runners: testexpressions
